// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/user/Domains/AuthRepository.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/user/Domains/AuthRepository.go -destination=src/modul/user/mocks/auth_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthenticationRepository is a mock of AuthenticationRepository interface.
type MockAuthenticationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticationRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthenticationRepositoryMockRecorder is the mock recorder for MockAuthenticationRepository.
type MockAuthenticationRepositoryMockRecorder struct {
	mock *MockAuthenticationRepository
}

// NewMockAuthenticationRepository creates a new mock instance.
func NewMockAuthenticationRepository(ctrl *gomock.Controller) *MockAuthenticationRepository {
	mock := &MockAuthenticationRepository{ctrl: ctrl}
	mock.recorder = &MockAuthenticationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthenticationRepository) EXPECT() *MockAuthenticationRepositoryMockRecorder {
	return m.recorder
}

// SaveRefreshToken mocks base method.
func (m *MockAuthenticationRepository) SaveRefreshToken(refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRefreshToken", refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRefreshToken indicates an expected call of SaveRefreshToken.
func (mr *MockAuthenticationRepositoryMockRecorder) SaveRefreshToken(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRefreshToken", reflect.TypeOf((*MockAuthenticationRepository)(nil).SaveRefreshToken), refreshToken)
}
