// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/user/Applications/security/AuthToken.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/user/Applications/security/AuthToken.go -destination=src/modul/user/mocks/mock_auth_token.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthToken is a mock of AuthToken interface.
type MockAuthToken struct {
	ctrl     *gomock.Controller
	recorder *MockAuthTokenMockRecorder
	isgomock struct{}
}

// MockAuthTokenMockRecorder is the mock recorder for MockAuthToken.
type MockAuthTokenMockRecorder struct {
	mock *MockAuthToken
}

// NewMockAuthToken creates a new mock instance.
func NewMockAuthToken(ctrl *gomock.Controller) *MockAuthToken {
	mock := &MockAuthToken{ctrl: ctrl}
	mock.recorder = &MockAuthTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthToken) EXPECT() *MockAuthTokenMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockAuthToken) GenerateToken(id string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockAuthTokenMockRecorder) GenerateToken(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockAuthToken)(nil).GenerateToken), id)
}

// ValidateToken mocks base method.
func (m *MockAuthToken) ValidateToken(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockAuthTokenMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockAuthToken)(nil).ValidateToken), tokenString)
}
