// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/user/Applications/security/HashPassword.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/user/Applications/security/HashPassword.go -destination=src/modul/user/mocks/mock_hash_password.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHashPassword is a mock of HashPassword interface.
type MockHashPassword struct {
	ctrl     *gomock.Controller
	recorder *MockHashPasswordMockRecorder
	isgomock struct{}
}

// MockHashPasswordMockRecorder is the mock recorder for MockHashPassword.
type MockHashPasswordMockRecorder struct {
	mock *MockHashPassword
}

// NewMockHashPassword creates a new mock instance.
func NewMockHashPassword(ctrl *gomock.Controller) *MockHashPassword {
	mock := &MockHashPassword{ctrl: ctrl}
	mock.recorder = &MockHashPasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashPassword) EXPECT() *MockHashPasswordMockRecorder {
	return m.recorder
}

// CompareHashPassword mocks base method.
func (m *MockHashPassword) CompareHashPassword(password, hashPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashPassword", password, hashPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashPassword indicates an expected call of CompareHashPassword.
func (mr *MockHashPasswordMockRecorder) CompareHashPassword(password, hashPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashPassword", reflect.TypeOf((*MockHashPassword)(nil).CompareHashPassword), password, hashPassword)
}

// HashingPassword mocks base method.
func (m *MockHashPassword) HashingPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashingPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashingPassword indicates an expected call of HashingPassword.
func (mr *MockHashPasswordMockRecorder) HashingPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashingPassword", reflect.TypeOf((*MockHashPassword)(nil).HashingPassword), password)
}
