// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/user/Domains/UserRepository.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/user/Domains/UserRepository.go -destination=src/modul/user/mocks/user_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "notes-app/src/modul/user/Domains/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Createuser mocks base method.
func (m *MockUserRepository) Createuser(user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Createuser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Createuser indicates an expected call of Createuser.
func (mr *MockUserRepositoryMockRecorder) Createuser(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Createuser", reflect.TypeOf((*MockUserRepository)(nil).Createuser), user)
}

// FindUserByUsername mocks base method.
func (m *MockUserRepository) FindUserByUsername(user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUsername", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindUserByUsername indicates an expected call of FindUserByUsername.
func (mr *MockUserRepositoryMockRecorder) FindUserByUsername(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUsername", reflect.TypeOf((*MockUserRepository)(nil).FindUserByUsername), user)
}

// VerifyUsername mocks base method.
func (m *MockUserRepository) VerifyUsername(user *entities.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUsername", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUsername indicates an expected call of VerifyUsername.
func (mr *MockUserRepositoryMockRecorder) VerifyUsername(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUsername", reflect.TypeOf((*MockUserRepository)(nil).VerifyUsername), user)
}
