// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/note/Applications/generator/id_generator.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/note/Applications/generator/id_generator.go -destination=src/modul/note/mocks/id_generator.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIdGenerator is a mock of IdGenerator interface.
type MockIdGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIdGeneratorMockRecorder
	isgomock struct{}
}

// MockIdGeneratorMockRecorder is the mock recorder for MockIdGenerator.
type MockIdGeneratorMockRecorder struct {
	mock *MockIdGenerator
}

// NewMockIdGenerator creates a new mock instance.
func NewMockIdGenerator(ctrl *gomock.Controller) *MockIdGenerator {
	mock := &MockIdGenerator{ctrl: ctrl}
	mock.recorder = &MockIdGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdGenerator) EXPECT() *MockIdGeneratorMockRecorder {
	return m.recorder
}

// Generator mocks base method.
func (m *MockIdGenerator) Generator() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generator")
	ret0, _ := ret[0].(string)
	return ret0
}

// Generator indicates an expected call of Generator.
func (mr *MockIdGeneratorMockRecorder) Generator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generator", reflect.TypeOf((*MockIdGenerator)(nil).Generator))
}
