// Code generated by MockGen. DO NOT EDIT.
// Source: src/modul/note/Domains/NotesRepository.go
//
// Generated by this command:
//
//	mockgen -source=src/modul/note/Domains/NotesRepository.go -destination=src/modul/note/mocks/NotesRepository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	entities "notes-app/src/modul/note/Domains/entities"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotesRepository is a mock of NotesRepository interface.
type MockNotesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotesRepositoryMockRecorder
	isgomock struct{}
}

// MockNotesRepositoryMockRecorder is the mock recorder for MockNotesRepository.
type MockNotesRepositoryMockRecorder struct {
	mock *MockNotesRepository
}

// NewMockNotesRepository creates a new mock instance.
func NewMockNotesRepository(ctrl *gomock.Controller) *MockNotesRepository {
	mock := &MockNotesRepository{ctrl: ctrl}
	mock.recorder = &MockNotesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesRepository) EXPECT() *MockNotesRepositoryMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockNotesRepository) CreateNote(note entities.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", note)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNotesRepositoryMockRecorder) CreateNote(note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNotesRepository)(nil).CreateNote), note)
}

// DeleteNoteById mocks base method.
func (m *MockNotesRepository) DeleteNoteById(note entities.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNoteById", note)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNoteById indicates an expected call of DeleteNoteById.
func (mr *MockNotesRepositoryMockRecorder) DeleteNoteById(note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNoteById", reflect.TypeOf((*MockNotesRepository)(nil).DeleteNoteById), note)
}

// EditNoteById mocks base method.
func (m *MockNotesRepository) EditNoteById(note entities.Note, update map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditNoteById", note, update)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditNoteById indicates an expected call of EditNoteById.
func (mr *MockNotesRepositoryMockRecorder) EditNoteById(note, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditNoteById", reflect.TypeOf((*MockNotesRepository)(nil).EditNoteById), note, update)
}

// FindNoteById mocks base method.
func (m *MockNotesRepository) FindNoteById(note *entities.Note) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNoteById", note)
	ret0, _ := ret[0].(error)
	return ret0
}

// FindNoteById indicates an expected call of FindNoteById.
func (mr *MockNotesRepositoryMockRecorder) FindNoteById(note any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNoteById", reflect.TypeOf((*MockNotesRepository)(nil).FindNoteById), note)
}

// GetAllNote mocks base method.
func (m *MockNotesRepository) GetAllNote(userId string) []entities.Note {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNote", userId)
	ret0, _ := ret[0].([]entities.Note)
	return ret0
}

// GetAllNote indicates an expected call of GetAllNote.
func (mr *MockNotesRepositoryMockRecorder) GetAllNote(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNote", reflect.TypeOf((*MockNotesRepository)(nil).GetAllNote), userId)
}
